<?php
// includes/admin_created.php - automatically generated by admin_signup.php
if (!defined('ADMIN_USER_IDS')) {
    define('ADMIN_USER_IDS', [25]);
}
if (!defined('ADMIN_DISPLAY_NAME')) {
    define('ADMIN_DISPLAY_NAME', 'Site Admin');
}
// Optional master admin id (primary account allowed to toggle signup)
if (!defined('ADMIN_MASTER_ID')) {
    // Use first ID from ADMIN_USER_IDS as default master
    define('ADMIN_MASTER_ID', (defined('ADMIN_USER_IDS') && is_array(ADMIN_USER_IDS) && count(ADMIN_USER_IDS) > 0) ? ADMIN_USER_IDS[0] : 0);
}
?>
